-- mods/default/aliases.lua

-- Aliases to support loading worlds using nodes following the old naming convention
-- These can also be helpful when using chat commands, for example /giveme
engine.register_alias("stone", "default:stone")
engine.register_alias("stone_with_coal", "default:stone_with_coal")
engine.register_alias("stone_with_iron", "default:stone_with_iron")
engine.register_alias("dirt_with_grass", "default:dirt_with_grass")
engine.register_alias("dirt_with_grass_footsteps", "default:dirt_with_grass_footsteps")
engine.register_alias("dirt", "default:dirt")
engine.register_alias("sand", "default:sand")
engine.register_alias("gravel", "default:gravel")
engine.register_alias("sandstone", "default:sandstone")
engine.register_alias("clay", "default:clay")
engine.register_alias("brick", "default:brick")
engine.register_alias("tree", "default:tree")
engine.register_alias("jungletree", "default:jungle_tree")
engine.register_alias("junglegrass", "default:jungle_grass")
engine.register_alias("leaves", "default:leaves")
engine.register_alias("cactus", "default:cactus")
engine.register_alias("papyrus", "default:papyrus")
engine.register_alias("bookshelf", "default:bookshelf")
engine.register_alias("glass", "default:glass")
engine.register_alias("wooden_fence", "default:fence_wood")
engine.register_alias("rail", "carts:rail")
engine.register_alias("ladder", "default:ladder_wood")
engine.register_alias("wood", "default:wood")
engine.register_alias("mese", "default:mese")
engine.register_alias("cloud", "default:cloud")
engine.register_alias("water_flowing", "default:water_flowing")
engine.register_alias("water_source", "default:water_source")
engine.register_alias("lava_flowing", "default:lava_flowing")
engine.register_alias("lava_source", "default:lava_source")
engine.register_alias("torch", "default:torch")
engine.register_alias("sign_wall", "default:sign_wall_wood")
engine.register_alias("furnace", "default:furnace")
engine.register_alias("chest", "default:chest")
engine.register_alias("locked_chest", "default:chest_locked")
engine.register_alias("cobble", "default:cobble")
engine.register_alias("mossycobble", "default:mossycobble")
engine.register_alias("ironblock", "default:ironblock")
engine.register_alias("steelblock", "default:steelblock")
engine.register_alias("sapling", "default:sapling")
engine.register_alias("apple", "default:apple")

engine.register_alias("WPick", "default:pick_wood")
engine.register_alias("STPick", "default:pick_stone")
engine.register_alias("IronPick", "default:pick_iron")
engine.register_alias("SteelPick", "default:pick_steel")
engine.register_alias("MesePick", "default:pick_mese")
engine.register_alias("WShovel", "default:shovel_wood")
engine.register_alias("STShovel", "default:shovel_stone")
engine.register_alias("IronShovel", "default:shovel_iron")
engine.register_alias("SteelShovel", "default:shovel_steel")
engine.register_alias("WAxe", "default:axe_wood")
engine.register_alias("STAxe", "default:axe_stone")
engine.register_alias("IronAxe", "default:axe_iron")
engine.register_alias("SteelAxe", "default:axe_steel")
engine.register_alias("WSword", "default:sword_wood")
engine.register_alias("STSword", "default:sword_stone")
engine.register_alias("IronSword", "default:sword_iron")
engine.register_alias("SteelSword", "default:sword_steel")

engine.register_alias("Stick", "default:stick")
engine.register_alias("paper", "default:paper")
engine.register_alias("book", "default:book")
engine.register_alias("lump_of_coal", "default:coal_lump")
engine.register_alias("charcoal", "default:charcoal")
engine.register_alias("lump_of_iron", "default:iron_lump")
engine.register_alias("lump_of_clay", "default:clay_lump")
engine.register_alias("iron_ingot", "default:iron_ingot")
engine.register_alias("steel_ingot", "default:steel_ingot")
engine.register_alias("clay_brick", "default:clay_brick")
engine.register_alias("snow", "default:snow")

--
-- Aliases for old node names
--

-- 'mese_block' was used for a while for the block form of mese
engine.register_alias("default:mese_block", "default:mese")

engine.register_alias("default:pinetree", "default:pine_tree")
engine.register_alias("default:pinewood", "default:pine_wood")

engine.register_alias("default:jungletree", "default:jungle_tree")
engine.register_alias("default:junglewood", "default:jungle_wood")
engine.register_alias("default:jungleleaves", "default:jungle_leaves")
engine.register_alias("default:junglesapling", "default:jungle_sapling")
engine.register_alias("default:junglegrass", "default:jungle_grass")
-- engine.register_alias("default_jungletree.png", "default_jungle_tree.png")
-- engine.register_alias("default_jungletree_top.png", "default_jungle_tree_top.png")
-- engine.register_alias("default_junglewood.png", "default_jungle_wood.png")
-- engine.register_alias("default_jungleleaves.png", "default_jungle_leaves.png")
-- engine.register_alias("default_jungleleaves_simple.png", "default_jungle_leaves_simple.png")
-- engine.register_alias("default_junglesapling.png", "default_jungle_sapling.png")
-- engine.register_alias("default_junglegrass.png", "default_jungle_grass.png")

engine.register_alias("default:ladder", "default:ladder_wood")
engine.register_alias("default:sign_wall", "default:sign_wall_wood")
